// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/cluster_services.proto

package ttnpb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() {
	proto.RegisterFile("lorawan-stack/api/cluster_services.proto", fileDescriptor_17685f40815dd3e5)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/cluster_services.proto", fileDescriptor_17685f40815dd3e5)
}

var fileDescriptor_17685f40815dd3e5 = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x3d, 0x4c, 0x14, 0x41,
	0x14, 0xde, 0x41, 0x73, 0xc6, 0x4d, 0x94, 0x38, 0x05, 0x92, 0x53, 0x1e, 0x71, 0xc1, 0x60, 0x88,
	0xb7, 0xa3, 0x10, 0x8d, 0xd1, 0x0a, 0x51, 0x2f, 0x24, 0x54, 0xa0, 0x16, 0xd7, 0x90, 0xbd, 0xbb,
	0x61, 0x6f, 0xc3, 0xb1, 0x73, 0xee, 0xcc, 0x41, 0x90, 0x5c, 0x42, 0xa8, 0xa0, 0x23, 0x31, 0x26,
	0x36, 0x24, 0xc6, 0x46, 0x3a, 0x29, 0x29, 0x29, 0x29, 0x49, 0x68, 0x28, 0xb9, 0x5d, 0x0b, 0x0a,
	0x0b, 0x4a, 0xec, 0xcc, 0xce, 0xee, 0x1e, 0x7b, 0x7f, 0x70, 0x97, 0xd8, 0xcd, 0xce, 0x7c, 0xef,
	0xbd, 0xef, 0xbd, 0xef, 0x9b, 0x59, 0xf5, 0x51, 0x91, 0x39, 0xc6, 0xb2, 0x61, 0xa7, 0xb8, 0x30,
	0x72, 0x0b, 0xc4, 0x28, 0x59, 0x24, 0x57, 0x2c, 0x73, 0x41, 0x9d, 0x39, 0x4e, 0x9d, 0x25, 0x2b,
	0x47, 0xb9, 0x5e, 0x72, 0x98, 0x60, 0xf8, 0xb6, 0x10, 0xb6, 0x1e, 0xa2, 0xf5, 0xa5, 0xf1, 0x64,
	0xca, 0xb4, 0x44, 0xa1, 0x9c, 0xd5, 0x73, 0x6c, 0x91, 0x98, 0xcc, 0x64, 0x44, 0xc2, 0xb2, 0xe5,
	0x79, 0xf9, 0x25, 0x3f, 0xe4, 0x2a, 0x08, 0x4f, 0xde, 0x37, 0x19, 0x33, 0x8b, 0x54, 0x56, 0x30,
	0x6c, 0x9b, 0x09, 0x43, 0x58, 0xcc, 0x0e, 0x93, 0x27, 0xef, 0x85, 0xa7, 0xb5, 0x1c, 0x74, 0xb1,
	0x24, 0x56, 0xc2, 0xc3, 0xc1, 0xb6, 0x1c, 0x43, 0xc0, 0x50, 0x33, 0xc0, 0xca, 0x53, 0x5b, 0x58,
	0xf3, 0x16, 0x75, 0xa2, 0x12, 0xd0, 0x0c, 0x72, 0x2c, 0xb3, 0x20, 0xc2, 0xf3, 0xb1, 0x5f, 0x37,
	0xd4, 0xde, 0xc9, 0x20, 0xed, 0x0c, 0x35, 0x2d, 0x2e, 0x9c, 0x15, 0x7c, 0x84, 0xd4, 0xc4, 0xa4,
	0x43, 0x0d, 0x41, 0xf1, 0xb0, 0x5e, 0xdf, 0xbf, 0x1e, 0xec, 0xd7, 0x22, 0x3e, 0x95, 0x29, 0x17,
	0xc9, 0xbb, 0x4d, 0xa8, 0xe0, 0x5c, 0xdb, 0x44, 0xeb, 0x47, 0xbf, 0xbf, 0xf4, 0xac, 0x23, 0x8d,
	0x90, 0x32, 0xa7, 0x0e, 0x27, 0xab, 0x39, 0x56, 0x2c, 0x1a, 0x59, 0xe6, 0x18, 0x82, 0x39, 0xba,
	0xbf, 0x37, 0x67, 0xe5, 0x79, 0xb4, 0xa8, 0x44, 0x2d, 0xf2, 0x97, 0x68, 0x34, 0x33, 0xad, 0xa5,
	0x09, 0x73, 0x4c, 0xc3, 0xb6, 0x3e, 0x07, 0x63, 0x6b, 0x88, 0x8e, 0x9f, 0xc9, 0x2c, 0x0d, 0x1b,
	0x75, 0xd9, 0xf0, 0xa2, 0x7a, 0x2d, 0x4d, 0x05, 0x7e, 0xd0, 0xc8, 0x35, 0x4d, 0x45, 0xa7, 0xed,
	0x8c, 0xca, 0x6e, 0x86, 0xb1, 0x56, 0x4b, 0x4c, 0x56, 0x23, 0xdf, 0xf8, 0xf5, 0x2f, 0xd6, 0x15,
	0xbc, 0x8d, 0xd4, 0xfe, 0x34, 0x15, 0x53, 0x17, 0x8a, 0xbc, 0x63, 0xce, 0x44, 0x3e, 0xef, 0x50,
	0xce, 0xf1, 0xf3, 0xf6, 0x24, 0x5a, 0x06, 0x44, 0xcc, 0xb4, 0x36, 0xcc, 0x62, 0x41, 0xda, 0x43,
	0x49, 0x72, 0x10, 0x0f, 0x44, 0x24, 0x53, 0x56, 0x9e, 0x18, 0x41, 0x1e, 0xb2, 0x1a, 0x2e, 0x2a,
	0xf8, 0x18, 0xa9, 0xd7, 0xa7, 0x2d, 0x2e, 0xf0, 0x50, 0x63, 0x4e, 0x7f, 0x37, 0xcc, 0x5b, 0x2b,
	0xdc, 0xdf, 0xa6, 0x30, 0xd7, 0xb6, 0x02, 0x89, 0x37, 0x11, 0xbe, 0x59, 0x9b, 0x4a, 0xe6, 0x29,
	0xee, 0x56, 0xef, 0xcc, 0x14, 0xfe, 0x5f, 0x62, 0xe3, 0x25, 0x35, 0xf1, 0xa1, 0x94, 0x6f, 0x69,
	0xdf, 0x60, 0xbf, 0x53, 0xbd, 0x53, 0xb2, 0xb5, 0x91, 0x64, 0x0b, 0xbd, 0xf5, 0x06, 0xbd, 0x7d,
	0x87, 0xe5, 0xd5, 0xc4, 0x1b, 0x5a, 0xa4, 0x82, 0xe2, 0x0e, 0x74, 0x4a, 0xf6, 0xe9, 0xc1, 0xed,
	0xd7, 0xa3, 0xdb, 0xaf, 0xbf, 0xf5, 0x6f, 0xbf, 0x06, 0xb2, 0x68, 0xff, 0x68, 0x5f, 0x4b, 0x93,
	0x55, 0xc6, 0x7e, 0x26, 0xd4, 0x5b, 0x61, 0xba, 0x89, 0x5c, 0xce, 0x77, 0x13, 0x53, 0x55, 0x5f,
	0xb3, 0x19, 0x79, 0xaf, 0x3b, 0xac, 0xdd, 0x80, 0x09, 0x62, 0x9b, 0xbd, 0x53, 0x5f, 0x3b, 0x7c,
	0x3a, 0xf0, 0x9f, 0x1e, 0xb5, 0xd7, 0x77, 0x6c, 0x4c, 0x1f, 0x9c, 0x6a, 0x6f, 0xe9, 0x38, 0x2e,
	0x9a, 0xf9, 0x48, 0x2b, 0x78, 0x1d, 0x8e, 0x97, 0x98, 0xcd, 0xa9, 0xb6, 0xd6, 0x23, 0x39, 0xfd,
	0x45, 0x98, 0x5c, 0x7d, 0xeb, 0x48, 0xdc, 0x32, 0x99, 0x8f, 0xf8, 0x7d, 0x97, 0x21, 0xd2, 0xb4,
	0x57, 0x79, 0x36, 0x63, 0xe3, 0x62, 0xb7, 0x79, 0xe3, 0x66, 0xed, 0xd6, 0xd8, 0xf8, 0x2b, 0x52,
	0x7b, 0x67, 0xaf, 0x1a, 0xf7, 0xec, 0xa5, 0xe3, 0x6e, 0x67, 0xb6, 0x57, 0x72, 0xb8, 0xcf, 0x92,
	0x4f, 0xba, 0x6c, 0x48, 0xbe, 0xa8, 0xdb, 0x48, 0xbd, 0x23, 0x1f, 0x8b, 0xf8, 0x01, 0x26, 0x97,
	0xbc, 0x27, 0x75, 0xc8, 0x88, 0xdb, 0x40, 0x93, 0x61, 0xe3, 0x28, 0xed, 0x85, 0xa4, 0x38, 0x86,
	0xbb, 0xa6, 0xf8, 0xfa, 0x07, 0x3a, 0xa8, 0x02, 0x3a, 0xac, 0x02, 0x3a, 0xae, 0x82, 0x72, 0x52,
	0x05, 0xe5, 0xb4, 0x0a, 0xca, 0x59, 0x15, 0x94, 0xf3, 0x2a, 0xa0, 0x35, 0x17, 0xd0, 0x86, 0x0b,
	0xca, 0x8e, 0x0b, 0x68, 0xd7, 0x05, 0x65, 0xcf, 0x05, 0x65, 0xdf, 0x05, 0xe5, 0xc0, 0x05, 0x74,
	0xe8, 0x02, 0x3a, 0x76, 0x41, 0x39, 0x71, 0x01, 0x9d, 0xba, 0xa0, 0x9c, 0xb9, 0x80, 0xce, 0x5d,
	0x50, 0xd6, 0x3c, 0x50, 0x36, 0x3c, 0x40, 0x5b, 0x1e, 0x28, 0xdf, 0x3c, 0x40, 0xdf, 0x3d, 0x50,
	0x76, 0x3c, 0x50, 0x76, 0x3d, 0x40, 0x7b, 0x1e, 0xa0, 0x7d, 0x0f, 0x50, 0xe6, 0xb1, 0xc9, 0x74,
	0x51, 0xa0, 0xa2, 0x60, 0xd9, 0x26, 0xd7, 0x6d, 0x2a, 0x96, 0x99, 0xb3, 0x40, 0xea, 0xff, 0xc3,
	0xa5, 0x05, 0x93, 0x08, 0x61, 0x97, 0xb2, 0xd9, 0x84, 0x54, 0x64, 0xfc, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdb, 0x46, 0x0c, 0xb1, 0x93, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterRegistryClient is the client API for ClusterRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterRegistryClient interface {
	Create(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*Cluster, error)
	// Get the cluster with the given identifiers, selecting the fields given
	// by the field mask.
	Get(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*Cluster, error)
	GetIdentifiersForAddress(ctx context.Context, in *GetClusterIdentifiersForAddressRequest, opts ...grpc.CallOption) (*ClusterIdentifiers, error)
	// List clusters, selecting the fields given by the field mask.
	List(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*Clusters, error)
	Update(ctx context.Context, in *UpdateClusterRequest, opts ...grpc.CallOption) (*Cluster, error)
	Delete(ctx context.Context, in *ClusterIdentifiers, opts ...grpc.CallOption) (*types.Empty, error)
}

type clusterRegistryClient struct {
	cc *grpc.ClientConn
}

func NewClusterRegistryClient(cc *grpc.ClientConn) ClusterRegistryClient {
	return &clusterRegistryClient{cc}
}

func (c *clusterRegistryClient) Create(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) Get(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) GetIdentifiersForAddress(ctx context.Context, in *GetClusterIdentifiersForAddressRequest, opts ...grpc.CallOption) (*ClusterIdentifiers, error) {
	out := new(ClusterIdentifiers)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/GetIdentifiersForAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) List(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*Clusters, error) {
	out := new(Clusters)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) Update(ctx context.Context, in *UpdateClusterRequest, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) Delete(ctx context.Context, in *ClusterIdentifiers, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterRegistryServer is the server API for ClusterRegistry service.
type ClusterRegistryServer interface {
	Create(context.Context, *CreateClusterRequest) (*Cluster, error)
	// Get the cluster with the given identifiers, selecting the fields given
	// by the field mask.
	Get(context.Context, *GetClusterRequest) (*Cluster, error)
	GetIdentifiersForAddress(context.Context, *GetClusterIdentifiersForAddressRequest) (*ClusterIdentifiers, error)
	// List clusters, selecting the fields given by the field mask.
	List(context.Context, *ListClustersRequest) (*Clusters, error)
	Update(context.Context, *UpdateClusterRequest) (*Cluster, error)
	Delete(context.Context, *ClusterIdentifiers) (*types.Empty, error)
}

func RegisterClusterRegistryServer(s *grpc.Server, srv ClusterRegistryServer) {
	s.RegisterService(&_ClusterRegistry_serviceDesc, srv)
}

func _ClusterRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).Create(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).Get(ctx, req.(*GetClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_GetIdentifiersForAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterIdentifiersForAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).GetIdentifiersForAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/GetIdentifiersForAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).GetIdentifiersForAddress(ctx, req.(*GetClusterIdentifiersForAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).List(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).Update(ctx, req.(*UpdateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).Delete(ctx, req.(*ClusterIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.ClusterRegistry",
	HandlerType: (*ClusterRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ClusterRegistry_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ClusterRegistry_Get_Handler,
		},
		{
			MethodName: "GetIdentifiersForAddress",
			Handler:    _ClusterRegistry_GetIdentifiersForAddress_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ClusterRegistry_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ClusterRegistry_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ClusterRegistry_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/cluster_services.proto",
}

// ClusterAccessClient is the client API for ClusterAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterAccessClient interface {
	ListRights(ctx context.Context, in *ClusterIdentifiers, opts ...grpc.CallOption) (*Rights, error)
	// Get the rights of a collaborator (member) of the cluster.
	// Pseudo-rights in the response (such as the "_ALL" right) are not expanded.
	GetCollaborator(ctx context.Context, in *GetClusterCollaboratorRequest, opts ...grpc.CallOption) (*GetCollaboratorResponse, error)
	// Set the rights of a collaborator (member) on the cluster.
	// Setting a collaborator without rights, removes them.
	SetCollaborator(ctx context.Context, in *SetClusterCollaboratorRequest, opts ...grpc.CallOption) (*types.Empty, error)
	ListCollaborators(ctx context.Context, in *ListClusterCollaboratorsRequest, opts ...grpc.CallOption) (*Collaborators, error)
}

type clusterAccessClient struct {
	cc *grpc.ClientConn
}

func NewClusterAccessClient(cc *grpc.ClientConn) ClusterAccessClient {
	return &clusterAccessClient{cc}
}

func (c *clusterAccessClient) ListRights(ctx context.Context, in *ClusterIdentifiers, opts ...grpc.CallOption) (*Rights, error) {
	out := new(Rights)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterAccess/ListRights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterAccessClient) GetCollaborator(ctx context.Context, in *GetClusterCollaboratorRequest, opts ...grpc.CallOption) (*GetCollaboratorResponse, error) {
	out := new(GetCollaboratorResponse)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterAccess/GetCollaborator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterAccessClient) SetCollaborator(ctx context.Context, in *SetClusterCollaboratorRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterAccess/SetCollaborator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterAccessClient) ListCollaborators(ctx context.Context, in *ListClusterCollaboratorsRequest, opts ...grpc.CallOption) (*Collaborators, error) {
	out := new(Collaborators)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterAccess/ListCollaborators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterAccessServer is the server API for ClusterAccess service.
type ClusterAccessServer interface {
	ListRights(context.Context, *ClusterIdentifiers) (*Rights, error)
	// Get the rights of a collaborator (member) of the cluster.
	// Pseudo-rights in the response (such as the "_ALL" right) are not expanded.
	GetCollaborator(context.Context, *GetClusterCollaboratorRequest) (*GetCollaboratorResponse, error)
	// Set the rights of a collaborator (member) on the cluster.
	// Setting a collaborator without rights, removes them.
	SetCollaborator(context.Context, *SetClusterCollaboratorRequest) (*types.Empty, error)
	ListCollaborators(context.Context, *ListClusterCollaboratorsRequest) (*Collaborators, error)
}

func RegisterClusterAccessServer(s *grpc.Server, srv ClusterAccessServer) {
	s.RegisterService(&_ClusterAccess_serviceDesc, srv)
}

func _ClusterAccess_ListRights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAccessServer).ListRights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterAccess/ListRights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAccessServer).ListRights(ctx, req.(*ClusterIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterAccess_GetCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAccessServer).GetCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterAccess/GetCollaborator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAccessServer).GetCollaborator(ctx, req.(*GetClusterCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterAccess_SetCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClusterCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAccessServer).SetCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterAccess/SetCollaborator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAccessServer).SetCollaborator(ctx, req.(*SetClusterCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterAccess_ListCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClusterCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAccessServer).ListCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterAccess/ListCollaborators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAccessServer).ListCollaborators(ctx, req.(*ListClusterCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterAccess_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.ClusterAccess",
	HandlerType: (*ClusterAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRights",
			Handler:    _ClusterAccess_ListRights_Handler,
		},
		{
			MethodName: "GetCollaborator",
			Handler:    _ClusterAccess_GetCollaborator_Handler,
		},
		{
			MethodName: "SetCollaborator",
			Handler:    _ClusterAccess_SetCollaborator_Handler,
		},
		{
			MethodName: "ListCollaborators",
			Handler:    _ClusterAccess_ListCollaborators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/cluster_services.proto",
}
