// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/cluster_services.proto

package ttnpb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() {
	proto.RegisterFile("lorawan-stack/api/cluster_services.proto", fileDescriptor_17685f40815dd3e5)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/cluster_services.proto", fileDescriptor_17685f40815dd3e5)
}

var fileDescriptor_17685f40815dd3e5 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3d, 0x68, 0x14, 0x41,
	0x14, 0xc7, 0x67, 0xa2, 0x08, 0xae, 0xa0, 0x38, 0x8d, 0xe1, 0xd0, 0x17, 0xdc, 0x28, 0x88, 0x78,
	0x33, 0x60, 0xc0, 0x5e, 0x05, 0x0f, 0xc1, 0xca, 0x4a, 0x6c, 0x64, 0xef, 0x76, 0x32, 0x37, 0xdc,
	0x65, 0xe6, 0x9c, 0x79, 0x97, 0x20, 0x21, 0x10, 0xac, 0x52, 0x0a, 0x36, 0x36, 0x82, 0x58, 0xa5,
	0x4c, 0x99, 0x32, 0x65, 0xca, 0x80, 0x4d, 0xca, 0xec, 0x8c, 0x45, 0xca, 0x94, 0xc1, 0x4a, 0x9c,
	0xdb, 0xbb, 0x98, 0xe8, 0x76, 0x6f, 0x76, 0xff, 0x1f, 0x3f, 0x1e, 0x2f, 0x7b, 0x30, 0xb4, 0xae,
	0x58, 0x2b, 0x4c, 0xdb, 0x63, 0xd1, 0x1b, 0x88, 0x62, 0xa4, 0x45, 0x6f, 0x38, 0xf6, 0x28, 0xdd,
	0x3b, 0x2f, 0xdd, 0xaa, 0xee, 0x49, 0xcf, 0x47, 0xce, 0xa2, 0x65, 0xd7, 0x11, 0x0d, 0xaf, 0xd5,
	0x7c, 0x75, 0xa9, 0xd5, 0x56, 0x1a, 0xfb, 0xe3, 0x2e, 0xef, 0xd9, 0x15, 0xa1, 0xac, 0xb2, 0x22,
	0xc9, 0xba, 0xe3, 0xe5, 0xf4, 0x4a, 0x8f, 0x34, 0x4d, 0xec, 0xad, 0xdb, 0xca, 0x5a, 0x35, 0x94,
	0xa9, 0xa1, 0x30, 0xc6, 0x62, 0x81, 0xda, 0x9a, 0x3a, 0xbc, 0xb5, 0xd0, 0x88, 0x51, 0x0b, 0x16,
	0xff, 0x15, 0xe8, 0x52, 0x1a, 0xd4, 0xcb, 0x5a, 0xba, 0x3a, 0xe5, 0xf1, 0xaf, 0xb9, 0xec, 0xc6,
	0xf3, 0x89, 0xed, 0xb5, 0x54, 0xda, 0xa3, 0xfb, 0xc0, 0x56, 0xb2, 0x4b, 0x1d, 0x89, 0xec, 0x2e,
	0x3f, 0x8f, 0xcf, 0x3b, 0x12, 0x67, 0xd2, 0xf7, 0x63, 0xe9, 0xb1, 0x75, 0xeb, 0xa2, 0xa4, 0xfe,
	0x9f, 0x3f, 0xfc, 0xf8, 0xe3, 0xe7, 0xe7, 0xb9, 0x7b, 0x2c, 0x9f, 0x32, 0x79, 0xb1, 0x3e, 0x5d,
	0x92, 0x2e, 0x3d, 0x3f, 0x9b, 0x37, 0xd8, 0x57, 0x9a, 0xcd, 0x77, 0x24, 0xbe, 0x3c, 0x63, 0x7b,
	0x61, 0xdd, 0xd3, 0xb2, 0x74, 0xd2, 0x7b, 0xf6, 0xa4, 0x19, 0xe2, 0xbf, 0x86, 0x29, 0x59, 0xde,
	0x40, 0xf6, 0x97, 0x29, 0xbf, 0x9f, 0x20, 0x17, 0xd8, 0x9d, 0x29, 0x64, 0x5b, 0x97, 0xa2, 0x98,
	0xe4, 0x88, 0xf5, 0x7a, 0xd8, 0x60, 0x6f, 0xb2, 0xcb, 0xaf, 0xb4, 0x47, 0xb6, 0x78, 0x31, 0xf2,
	0xcf, 0xd7, 0x3a, 0x76, 0xd6, 0x3b, 0xdf, 0xd0, 0xeb, 0xf3, 0x9b, 0xa9, 0xed, 0x1a, 0xbb, 0x3a,
	0x5b, 0xc9, 0xb3, 0xef, 0x74, 0xbf, 0x02, 0x7a, 0x50, 0x01, 0x3d, 0xac, 0x80, 0x1c, 0x55, 0x40,
	0x8e, 0x2b, 0x20, 0x27, 0x15, 0x90, 0xd3, 0x0a, 0xe8, 0x66, 0x00, 0xba, 0x15, 0x80, 0x6c, 0x07,
	0xa0, 0x3b, 0x01, 0xc8, 0x6e, 0x00, 0xb2, 0x17, 0x80, 0xec, 0x07, 0xa0, 0x07, 0x01, 0xe8, 0x61,
	0x00, 0x72, 0x14, 0x80, 0x1e, 0x07, 0x20, 0x27, 0x01, 0xe8, 0x69, 0x00, 0xb2, 0x19, 0x81, 0x6c,
	0x45, 0xa0, 0x9f, 0x22, 0x90, 0x2f, 0x11, 0xe8, 0xb7, 0x08, 0x64, 0x3b, 0x02, 0xd9, 0x89, 0x40,
	0x77, 0x23, 0xd0, 0xbd, 0x08, 0xf4, 0xed, 0x23, 0x65, 0x39, 0xf6, 0x25, 0xf6, 0xb5, 0x51, 0x9e,
	0x1b, 0x89, 0x6b, 0xd6, 0x0d, 0xc4, 0xf9, 0x6b, 0x19, 0x0d, 0x94, 0x40, 0x34, 0xa3, 0x6e, 0xf7,
	0x4a, 0x3a, 0x94, 0xa5, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x6e, 0xe6, 0xfd, 0xf7, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterRegistryClient is the client API for ClusterRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterRegistryClient interface {
	// Get the cluster with the given identifiers, selecting the fields given
	// by the field mask.
	Get(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*Cluster, error)
	GetIdentifiersForAddress(ctx context.Context, in *GetClusterIdentifiersForAddressRequest, opts ...grpc.CallOption) (*ClusterIdentifiers, error)
	// List clusters, selecting the fields given by the field mask.
	List(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*Clusters, error)
}

type clusterRegistryClient struct {
	cc *grpc.ClientConn
}

func NewClusterRegistryClient(cc *grpc.ClientConn) ClusterRegistryClient {
	return &clusterRegistryClient{cc}
}

func (c *clusterRegistryClient) Get(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) GetIdentifiersForAddress(ctx context.Context, in *GetClusterIdentifiersForAddressRequest, opts ...grpc.CallOption) (*ClusterIdentifiers, error) {
	out := new(ClusterIdentifiers)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/GetIdentifiersForAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRegistryClient) List(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*Clusters, error) {
	out := new(Clusters)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ClusterRegistry/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterRegistryServer is the server API for ClusterRegistry service.
type ClusterRegistryServer interface {
	// Get the cluster with the given identifiers, selecting the fields given
	// by the field mask.
	Get(context.Context, *GetClusterRequest) (*Cluster, error)
	GetIdentifiersForAddress(context.Context, *GetClusterIdentifiersForAddressRequest) (*ClusterIdentifiers, error)
	// List clusters, selecting the fields given by the field mask.
	List(context.Context, *ListClustersRequest) (*Clusters, error)
}

func RegisterClusterRegistryServer(s *grpc.Server, srv ClusterRegistryServer) {
	s.RegisterService(&_ClusterRegistry_serviceDesc, srv)
}

func _ClusterRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).Get(ctx, req.(*GetClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_GetIdentifiersForAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterIdentifiersForAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).GetIdentifiersForAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/GetIdentifiersForAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).GetIdentifiersForAddress(ctx, req.(*GetClusterIdentifiersForAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ClusterRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServer).List(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.ClusterRegistry",
	HandlerType: (*ClusterRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ClusterRegistry_Get_Handler,
		},
		{
			MethodName: "GetIdentifiersForAddress",
			Handler:    _ClusterRegistry_GetIdentifiersForAddress_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ClusterRegistry_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/cluster_services.proto",
}
